### ISSUE TITLE
Occasionally only lists one viewed page

### ISSUE THREAD

**Issue by nickom** [sunlightlabs/hanuman#1]
I've noticed a number of times that the tool will only detect a single page that I browsed, even after I've identified a number of lobbyists and visited a bunch of pages on the site. It could be weirdness with how the site is structured, but it's fooling hanuman into thinking I was only at the homepage of a firm...

Two examples:
![screen shot 2015-05-12 at 4 17 29 pm](https://cloud.githubusercontent.com/assets/3171982/7597707/45d18ac0-f8c3-11e4-9966-f072bae61d38.png)

![screen shot 2015-05-07 at 2 13 02 pm](https://cloud.githubusercontent.com/assets/3171982/7597711/489a9152-f8c3-11e4-9d64-3789e1f75ad5.png)

**Comment by apendleton** [comment]
Hm... on some level, I think the hackiness of this thing will probably just mean there are some sites we don't work with, and the first one, in particular, is structured in a way that's hard to work around... the second is maybe fixable, but I'm not sure.

Either way: maybe there should be an option for "this looks wrong; skip submitting the visit log for this firm"?

**Comment by nickom** [comment]
:+1:

**Comment by apendleton** [comment]
This was fixed in 0c2b2f66cb5166469f84677b61c205bb70b5e729
